### ISSUE TITLE
the menu isn't active after it's clicked

### ISSUE THREAD

**Issue by Alfana** [dropways/deskapp#14]
### Steps to reproduce

1. install the template into the codeigniter format
2. if I click one of the menus that are made, the menu is not automatically active
3. 

### Expected result

1. when clicked the menu will automatically active

### Actual result

1. after click menu not active 
![image](https://user-images.githubusercontent.com/25434155/61507302-652a1980-aa0f-11e9-8f75-b72051f00369.png)
2. my code
![image](https://user-images.githubusercontent.com/25434155/61507318-75da8f80-aa0f-11e9-902e-e7864f93beeb.png)
3. header
![image](https://user-images.githubusercontent.com/25434155/61507338-91459a80-aa0f-11e9-85c9-7ec9a0dd25f0.png)
4. footer
![image](https://user-images.githubusercontent.com/25434155/61507356-a15d7a00-aa0f-11e9-8336-060a2add79a5.png)

is there something wrong with the code? or what should I do?

**Comment by dropways** [comment]
Hi @Alfana 

Thanks for using Deskapp.

here is the solution for active class please check it
https://gist.github.com/sadanandkenganal/5f60461112b051dde5ab
https://forum.codeigniter.com/thread-62075.html

Thank you.
