### ISSUE TITLE
Printing Document

### ISSUE THREAD

**Issue by kristian0008** [dropways/deskapp#15]
how to change the text DeskApp Dashboard on printing a document or in DataTable? response pls

**Comment by dropways** [comment]
hi @kristian0008 

can you please change your project name in <head> tag in <title>Type your project name</title>

Thank you.

**Comment by kristian0008** [comment]
Thank you sir.
What if i change design? where can i see the php file of the pdf file sir?

**Comment by dropways** [comment]
if you want to change **PDF** design use **dompdf** and create custom html inside pdf
http://www.globalvolunteernetwork.org/include/dompdf/www/examples.php

**Comment by swapnilgawande143** [comment]
Taking to much time to load resources. Is there any way to reduce loading time?
