### ISSUE TITLE
Separate Bootstrap css an site css

### ISSUE THREAD

**Issue by ProjectLinde37** [dropways/deskapp#18]
Is it possible to separate the bootstrap css from the vendors/styles/style.css?
It should be easier to upgrade bootstrap

**Comment by dropways** [comment]
Hi @ProjectLinde37 

yes you can separate the bootstrap style. just follow the step

1) Remove bootstrap css and js file inside gulpfile.js
2) after remove css and js you need to run gulp watch command
3) attach css in include/head.php file 
4) attach js in include/script.php file

Thank you
