### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by jack96489** [dropways/deskapp#19]
Hi,
I report you that the [demo page](https://deskapp-dashboard.herokuapp.com/) is not working.
![image](https://user-images.githubusercontent.com/36044679/80577379-1631fb80-8a07-11ea-8cc9-9c2ab83366f6.png)

**Comment by dropways** [comment]
@jack96489  yes i know 

Sorry for the trouble

Because I'm using a free server so that's the problem

Thank you.
