### ISSUE TITLE
Highcharts issue

### ISSUE THREAD

**Issue by Vlad4GH** [dropways/deskapp#24]
### Steps to reproduce
add to "vendors\scripts\highchart-setting.js" for chart1:
Highcharts.chart('chart1', {
	chart: {
		type: 'spline'
	},
	plotOptions: {
		spline: {
      marker: {
        enabled: false
      }
    },
		series: {
			label: {
				connectorAllowed: false
			},
			pointStart: 2010
		}
	},

### Expected result
no datapoint symbols on lines and colored dashes as prefix for legend
### Actual result
no datapoint symbols on lines and no prefix for legend

If you want to get line chart without datapoints symbols, you should add follow code:
plotOptions: {	spline: { marker: {    enabled: false   }  }   }
But it also removes colored prefixes from legend. Originally, it should remove only symbols from legend, but left colored lines as prefix for line labels.
![Issue](https://user-images.githubusercontent.com/68547117/87942616-88b1f500-caa5-11ea-9b9b-538387a8fe03.JPG)
![ShouldBe](https://user-images.githubusercontent.com/68547117/87942618-89e32200-caa5-11ea-9ec5-2e82798b1ff1.JPG)
![WithMarker](https://user-images.githubusercontent.com/68547117/87942620-89e32200-caa5-11ea-84ee-c182c02f603f.JPG)

**Comment by dropways** [comment]
Hello @Vlad4GH 

please check new code

**Comment by Vlad4GH** [comment]
Now it's working properly.
Thanks.
