### ISSUE TITLE
Herokuapp Demo Not working

### ISSUE THREAD

**Issue by techierathore** [dropways/deskapp#25]
### Steps to reproduce
Came to know about this theme from Themewagon (https://themewagon.com/themes/free-bootstrap-4-html5-responsive-admin-dashboard-template-deskapp/) and wanted to use this for my cross-platform desktop app. but sample there is not working same as the Herokuapp Demo mentioned in the readme.
Just click on second sample link : https://deskapp-dashboard.herokuapp.com/ 
### Expected result
Should open the Demo 

### Actual result (Screem Message)
 Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by dropways** [comment]
Hello @techierathore 

Please check README.md File i have add new demo link also

Here is second demo link https://dropways.github.io/deskapp/

Thank you

**Comment by techierathore** [comment]
Hi Ankit, 
 Thanks for quick response, Actually I wanted to seee the UI shown on ThemeWagon Page like this  <img width="776" alt="Screenshot 2020-08-26 at 11 08 43 AM" src="https://user-images.githubusercontent.com/7636999/91259626-8457b680-e78c-11ea-8f10-c90f62d02550.png">

I thought that two links are to show the Dashboard in two ways. If both of these are the same then It's not an issue.
