### ISSUE TITLE
[Question] Why does the scrollbar extend up into the top nav?

### ISSUE THREAD

**Issue by PerryCodes** [dropways/deskapp#28]
The first thing I noticed after encountering this admin template was how clean and polished it looked.

Not 2 seconds later I was surprised by the way the top nav continues to change position every time a modal dialog is displayed - causing the scrollbar to disappear.  Because the scrollbar extends the entire length of the page - including the top nav - when the scrollbar disappears, the top nav shifts right... when the scrollbar reappears, the top nav shifts back left!

Is there a way to not extend up into the top nav?  The "main-container" and "header" divs are completely separate, so I assume this behavior is being affected by JavaScript somewhere?  Whatever is responsible for this behavior... I don't think it's desirable.

Jason

**Comment by dropways** [comment]
hello @PerryCodes 

Please send a video for this issue i didn't getting your point.

Thank you.
