### ISSUE TITLE
Icons not responding

### ISSUE THREAD

**Issue by ozmagic66** [dropways/deskapp#36]
Hello, the template at the moment works perfectly but when creating an html within a directory not in the root, the icons disappear. I would greatly appreciate an answer to be able to solve it. Best regards.
![Captura](https://user-images.githubusercontent.com/72042954/104956391-cb984b00-59aa-11eb-8c7c-d35c75c6440d.PNG)

**Comment by dropways** [comment]
Hello @ozmagic66 

Please check css and font files attached or not.

Thank you
