### ISSUE TITLE
how to fetch row values on checkbox selection?

### ISSUE THREAD

**Issue by KrupaVasava** [dropways/deskapp#47]
### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by dropways** [comment]
Hello @KrupaVasava 

Here is the demo link please check.

https://jsfiddle.net/nwmmbLso/3/

**Comment by KrupaVasava** [comment]
Thank you So much  it's working.
really appreciate your help

**Comment by KrupaVasava** [comment]
Hi

I need your help in all check box selection.

Please check below screenshot

Screenshot -1
![image](https://user-images.githubusercontent.com/105635359/179166122-fa00dd1d-d335-4ae7-8dfb-c33c4a403aea.png)
