### ISSUE TITLE
Dark Mode and Bootstrap v5 plsssss

### ISSUE THREAD

**Issue by haxvzje** [dropways/deskapp#58]
Pls add Dark Mode and Bootstrap v5

**Comment by dropways** [comment]
We are currently developing a new theme with a light and dark mode based on Bootstrap v5. We'll have lunch soon.

**Comment by haxvzje** [comment]
bro i love u so much

**Comment by DavidChriss** [comment]
> We are currently developing a new theme with a light and dark mode based on Bootstrap v5. We'll have lunch soon.

Thank you.. Can you also add option to lock and unlock sidebar when needed.. Sometimes I like to lock sidebar so I can have large space on seeing the table.. Thanks

**Comment by mehmetsarr** [comment]
> açık

We are waiting for Boostrap 5 and a more modern theme. Best regards.

**Comment by COD3HUNT3R** [comment]
I made bootstrap 5 version(only css). Updating to bootstrap 5 js breaks the dropdown. Also working on the night mode. Will see if I can fix those.
