### ISSUE TITLE
google map error

### ISSUE THREAD

**Issue by Fatihcan88** [dropways/deskapp#8]

**Comment by dropways** [comment]
Hello @Fatihcan88 ,

We are not able to understand the exact issue. Can you please post the steps to reproduce.

As we are not using Google Maps in built 

Thank you.

**Comment by Fatihcan88** [comment]
https://prnt.sc/kstnpg

script.asp line 4567

function _inheritsLoose(subClass, superClass) {
subClass.prototype = Object.create(superClass.prototype);
subClass.prototype.constructor = subClass;
subClass.proto = superClass;
}

delete 
https://prnt.sc/kstnk6
